Json to midi#31
Tonejs/MidiConvert pull request #33
Opened 2017-05-06 13:48 UTC by BartoszBaczek

Concerns issue #31 Added method allowing for deserializing to Midi object.

List of changes:
a) added `deserialize(json)` method to `MidiConvert`
b) added `fromJSON(json)` method to `Midi, Track, Note`
c) updated tests & d.ts definitions

2017-05-06 15:51 UTC, BartoszBaczek commented
Hi, i guess that's it. Should close it now, or what? I't my first pull request.

2017-05-06 16:33 UTC, appsforartists requested changes

2017-05-06 16:33 UTC, appsforartists commented on src/Midi.js
> +	fromJSON(json){
I would make this a static method.  (`encode` probably should be too, but that's a separate conversation).

2017-05-06 16:33 UTC, appsforartists commented on src/MidiConvert.js
> +	deserialize : function(json){
Let's also call this `fromJSON`

2017-05-06 16:33 UTC, appsforartists commented on test/test.js
> +	it("can decode track from JSON", function(){
Does this test anything the other one you added doesn't?

2017-05-06 16:33 UTC, appsforartists commented on src/Track.js
> +	fromJSON(json){
This should also be `static` (which means it should go at the top of the class).

2017-05-06 16:34 UTC, appsforartists commented
@BartoszBaczek Please make the requested changes here.

If you change your summary from "Concerns #31" to "Closes #31", your issue will automatically close when this lands.

2017-05-06 16:47 UTC, appsforartists commented
Also, the name of this PR will be the name of your commit, so I'd change it to "added fromJSON"

2017-05-07 14:31 UTC, BartoszBaczek commented on test/test.js
> +	it("can decode track from JSON", function(){
You're right, those are already tested in 'is jSON deserializable'

2017-05-07 15:00 UTC, BartoszBaczek commented
Done.

2017-05-07 16:49 UTC, appsforartists commented
Great!

Your static methods should be at the very top of their classes, before the constructor:

```typescript
class Midi {
  static fromJSON(json) {}
  
  constructor () {}
}
```

2017-05-08 15:40 UTC, BartoszBaczek commented
Done :) May I ask, when are you planning to bump npm package?

2017-05-08 16:20 UTC, appsforartists approved these changes

2017-05-08 16:20 UTC, appsforartists commented on src/MidiConvert.d.ts
> +export function fromJSON(json: object): MIDI;
I wonder if `Partial<MIDI>` is a more accurate type for `json`.  `json` should have the same shape as `MIDI`, just without the methods, right?

2017-05-08 16:21 UTC, appsforartists commented
I'm not an owner of this repo, so I can't comment on that.  You'd have to ask @tambien.

2017-05-08 16:51 UTC, appsforartists commented
One more thing: the first message in this thread will become the commit message, so you should update it.

2017-05-12 02:41 UTC, merged

2017-05-12 02:42 UTC, tambien commented
thank you!